### ISSUE TITLE
Incomplete package install

### ISSUE THREAD

**Issue by madig** [David-OConnor/pyflow#32]
1. Create a new project
2. Run `pyflow install ufolib2`

```
$ pyflow install ufolib2
Found lockfile
⬇ Installing ufolib2 0.5.1 ...
⬇ Installing attrs 19.3.0 ...
Installation complete
```

It should also install fonttools, see https://github.com/fonttools/ufoLib2/blob/master/setup.cfg. Not sure what's going on there.

**Comment by David-OConnor** [comment]
The requirement is listed as `"fonttools[ufo] (>=3.34.0)"` on Pypi. I'm not sure what the brackets and ufo mean, but this is a bug with parsing this format.

**Comment by David-OConnor** [comment]
Fixed in latest commit.

**Comment by madig** [comment]
Well, brackets are the `features = [...]` of the Python world, so they should not be ignored 😁 In this case, the `ufo` feature is required to make ufoLib2 work at all.

**Comment by David-OConnor** [comment]
Latest commit now handles this.

**Comment by madig** [comment]
Just tried `pyflow install ufolib2` again and it doesn't install fonttools?

**Comment by David-OConnor** [comment]
Try removing `pyflow.lock`, or running `pyflow reset`. I suspect this is due to the improper dependencies having been locked.

**Comment by madig** [comment]
Nope, this is with a freshly init'd project.

**Comment by David-OConnor** [comment]
What OS?

**Comment by madig** [comment]
Fedora 31 x86_64, Python 3.7.5.

```toml
[tool.pyflow]
name = ""
py_version = "3.7"
version = "0.1.0"
authors = ["Nikolaus Waxweiler <madigens@gmail.com>"]


[tool.pyflow.scripts]


[tool.pyflow.dependencies]
ufolib2 = "^0.5.1"


[tool.pyflow.dev-dependencies]
```
